export const RoutePath = Object.freeze({
  HomePage: '/',
  SanPhamPage: '/san-pham',
  DichVuPage: '/dich-vu',
  HoTroPage: '/ho-tro',
  ChiaSePage: '/chia-se',
  CongCu: '/cong-cu',
  FAQ: '/cau-hoi-thuong-gap',
  LoginPage: '/dang-nhap',
  SharePostList: '/post-list',
  MyPost: '/my-post',
  AddPost: '/post-add',

  // Stall
  stall: '/stall',
  sales: '/stall/sales',
  orderManage: '/stall/order-manager',
  productOrders: '/stall/product-orders',
  preOrders: '/stall/pre-orders',
  complain: '/stall/complain',
  replyComment: '/stall/reply-comment',
  promotion: '/stall/promotion',
  resellerManage: '/stall/resellerManage',
  topKiosk: '/stall/top-kiosk',
  AddPosShall: '/add-post',
  Chatbox: '/chat-box',
  EmailPage: '/danh-muc/email',
  AccountPage: '/danh-muc/tai-khoan',
  SoftwarePage: '/danh-muc/phan-mem',
  ProductOtherPage: '/danh-muc/danh-muc-khac',
  IncrementInteractPage: '/danh-muc/dich-vu-tuong-tac',
  BlockchainPage: '/danh-muc/dich-vu-blockchain',
  ServiceSoftwarePage: '/danh-muc/dich-vu-phan-mem',
  ServiceOtherPage: '/danh-muc/dich-vu-khac',
})
