export const RoutePath = Object.freeze({
  HomePage: '/',
  SanPhamPage: '/san-pham',
  DichVuPage: '/dich-vu',
  HoTroPage: '/ho-tro',
  ChiaSePage: '/chia-se',
  CongCu: '/cong-cu',
  FAQ: '/cau-hoi-thuong-gap',
  Regulation: '/quy-dinh',
  Authen2FA: '/2FA',
  CheckLiveFB: '/check-live-facebook',
  LoginPage: '/dang-nhap',
  SharePostList: '/post-list',
  MyPost: '/my-post',
  AddPost: '/post-add',
  AccessDenied: 'access-denied',
  ProductDetail: '/gian-hang/gmail-ngoai-new-ios-random-ip-ngam-tren-14_728121',

  // Stall
  Stall: '/stall',
  Sales: '/sales',
  OrderManage: '/quan-ly-gian-hang',
  ProductOrders: '/don-hang-san-pham',
  ServiceOrders: '/don-hang-dich-vu',
  PreOrders: '/dat-truoc',
  Complain: '/khieu-nai',
  ResellerManage: '/quan-ly-reseller',
  ReplyComment: '/danh-gia',
  Promotion: '/ma-giam-gia',
  TopKiosk: '/gian-hang-top-1',
  AddPosShall: '/add-post',
  Chatbox: '/chat-box',
  EmailPage: '/danh-muc/email',
  AccountPage: '/danh-muc/tai-khoan',
  SoftwarePage: '/danh-muc/phan-mem',

  // User Information
  UserInformationPage: '/thong-tin',
  OrderItemPage: '/orders-buy',
  WishListPage: '/wish-list',
  PaymentsPage: '/payments',
  Reseller: '/reseller',
  ChangePassword: '/change-password',

  ProductOtherPage: '/danh-muc/danh-muc-khac',
  IncrementInteractPage: '/danh-muc/dich-vu-tuong-tac',
  BlockchainPage: '/danh-muc/dich-vu-blockchain',
  ServiceSoftwarePage: '/danh-muc/dich-vu-phan-mem',
  ServiceOtherPage: '/danh-muc/dich-vu-khac',
  LikeProductPage: 'gian-hang-yeu-thich',
  Forgotpassword: '/quen-mat-khau',

  // Admin
  DashboardPage: '/admin',
  ManagerProductPage: '/admin/quan-ly-san-pham',
  ManagerServicePage: '/admin/quan-ly-dich-vu',
  ManagerBussinessTypePage: '/admin/quan-ly-loai-kinh doanh',
  ManagerShopTypePage: '/admin/quan-ly-loai-cua-hang',
  ManagerProductTypePage: '/admin/quan-ly-loai-san-pham',
  ManagerShopPage: '/admin/quan-ly-cua-hang',
  ManagerUserPage: '/admin/quan-ly-nguoi-dung',
  ManagerDiscountPage: '/admin/quan-ly-giam-gia',
  ManagerOrderComplainPage: '/admin/quan-ly-hoa-don-danh-gia',
  ManagerOrderPage: '/admin/quan-ly-hoa-don',
  ManagerShopReviewPage: '/admin/quan-ly-danh-gia-shop',
  ManagerShopEvalutionPage: '/admin/quan-ly-danh-gia-cua-hang',
})
