export const RoutePath = Object.freeze({
  HomePage: '/',
  SanPhamPage: '/san-pham',
  DichVuPage: '/dich-vu',
  HoTroPage: '/ho-tro',
  ChiaSePage: '/chia-se',
  CongCu: '/cong-cu',
  FAQ: '/cau-hoi-thuong-gap',
  LoginPage: '/dang-nhap',
  SharePostList: '/post-list',
  MyPost: '/my-post',
  AddPost: '/post-add',
  EmailPage: '/danh-muc/email',
  AccountPage: '/danh-muc/tai-khoan',
  SoftwarePage: '/danh-muc/phan-mem',
})
